 DROP TABLE Producers;
 CREATE TABLE Producers (
Producer                         char(20), 
Sklad                            char(15));
insert into Producers values('','');
insert into Producers values('"Пулковский Меридиан','1');
insert into Producers values('"РК им.Ленина"','БН');
insert into Producers values('"ШТУРМАН"','бн');
insert into Producers values('БАМР','БН');
insert into Producers values('БАТМ "АНИВА"','БН');
insert into Producers values('БАТМ "БОРИСОВ"','972');
insert into Producers values('БАТМ "БОРИСОВО"','');
insert into Producers values('БАТМ "Бутовск"','');
insert into Producers values('БАТМ "Полукс"','БН');
insert into Producers values('БАТМ "Сероглазка"','');
insert into Producers values('БАТМ"Г.Широнинцы"','Справка');
insert into Producers values('БАТМ"М.ДАЛЬНИЙ"','АП ДКХ');
insert into Producers values('БАТМ"П.МЕРИДИАН"','205');
insert into Producers values('БАТМ"П.НИКОЛАЕВА"','2240');
insert into Producers values('БАТМ"ПОЛЛУКС"','91');
insert into Producers values('БАТМ"Петропавловск"','964');
insert into Producers values('БАТМ"СЕРОГЛАЗКА"','');
insert into Producers values('БМРТ"А.Беляков"','002502');
insert into Producers values('БМРТ"Б.Преображение"','2106');
insert into Producers values('БМРТ"В.СТРЕЛЬЦОВ"','Справка');
insert into Producers values('БМРТ"И.МАЛЯКИН"','129');
insert into Producers values('БМРТ"ИХТИОЛОГ"','Справка');
insert into Producers values('БМРТ"ЙОХАН КЕЛЕР"','1541');
insert into Producers values('БМРТ"М.БАБУШКИНА"','');
insert into Producers values('БМРТ"М.КРЫЛОВА"','494');
insert into Producers values('БМРТ"П.ПАНИН"','191');
insert into Producers values('БМРТ"ПАХАЧА"','983');
insert into Producers values('БМРТ"РЕЗОЛЮТ"','528');
insert into Producers values('БМТР"Б.Преображение"','2106');
insert into Producers values('БОРИСОВО','');
insert into Producers values('Байковск','1618');
insert into Producers values('Большерецк Скит','БН');
insert into Producers values('Бутовск','');
insert into Producers values('Бухта Андреева','БН');
insert into Producers values('В.КАЛЕНОВ','БН');
insert into Producers values('ВАЗИКОВ','БН');
insert into Producers values('ВИНОГРАДОВКА','БН');
insert into Producers values('ВЛАДРЫБМАРИН','БН');
insert into Producers values('Витязь-Авто','БН');
insert into Producers values('Владрыбмарин','БН');
insert into Producers values('Восток1','бн');
insert into Producers values('ГРАНИК','бн');
insert into Producers values('ДАЛЬРЫБТОРГ','');
insert into Producers values('Диденко','383986');
insert into Producers values('Житников','142486');
insert into Producers values('ЗАЛИВ ВОСТОК','000150');
insert into Producers values('Залив Восток','000150');
insert into Producers values('ИОЛАНТА','229');
insert into Producers values('ИП Борисик А.П.','БН');
